// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsR_YWHsEtD7XUvc4vhdV22MWAYpZHiIE',
    appId: '1:284091339508:web:1bc3e6f31b3e583a59c4a1',
    messagingSenderId: '284091339508',
    projectId: 'code-camp-6193f',
    authDomain: 'code-camp-6193f.firebaseapp.com',
    storageBucket: 'code-camp-6193f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKEapy0BnfwJqFpL-jjm3dwVPkRdV7eg',
    appId: '1:284091339508:android:440d6fc0f761a52359c4a1',
    messagingSenderId: '284091339508',
    projectId: 'code-camp-6193f',
    storageBucket: 'code-camp-6193f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtYi8LxV8LZwJFcRLpTH6FyMRsmT-GN1o',
    appId: '1:284091339508:ios:234f3e49b2654a6c59c4a1',
    messagingSenderId: '284091339508',
    projectId: 'code-camp-6193f',
    storageBucket: 'code-camp-6193f.appspot.com',
    iosBundleId: 'com.example.testingProject12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtYi8LxV8LZwJFcRLpTH6FyMRsmT-GN1o',
    appId: '1:284091339508:ios:1145ecb50960d76f59c4a1',
    messagingSenderId: '284091339508',
    projectId: 'code-camp-6193f',
    storageBucket: 'code-camp-6193f.appspot.com',
    iosBundleId: 'com.example.testingProject.RunnerTests',
  );
}
